version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cineperu_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01deabril
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./cineperu-backend
    container_name: cineperu_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:01deabril@db:5432/postgres
      JWT_SECRET: supersecreto123
    depends_on:
      - db

volumes:
  postgres_data:
