services:
  db:
    image: postgres:15
    container_name: cineperu_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01deabril
      POSTGRES_DB: cineperu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./cineperu-backend
    container_name: cineperu_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:zBOEpCmUyJeyrZzzlBLAuFzNNBEhlZSt@metro.proxy.rlwy.net:30708/railway
      JWT_SECRET: supersecreto123
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
   